language: generic
os: osx

git:
  depth: false

before_install:
  - pip3 install cython

install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew upgrade proj 
  - pip3 install setuptools --upgrade
  - pip3 install --no-use-pep517 cartopy
  - pip3 install -r requirements.txt
  - pip3 install -e .

notifications:
  email:
    on_success: always 
    on_failure: always