language: generic
os: osx

git:
  depth: false

script:
  - python3 -m pip install sphinx
  - python3 -m pip install guzzle_sphinx_theme
  - cd docs
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  