language: generic
os: linux

git:
  depth: false

deploy:
  provider: pages
  skip-cleanup: true
  email: conorcaseyc@icloud.com
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: ./docs/build/html
  on:
    branch: master