language: generic
os: osx

git:
  depth: false

install:
  - pip install codecov
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c amsimp amsimp
  - conda uninstall amsimp
  - pip install pynverse
  - pip install wget
  - python3 -m pip install sphinx
  - python3 -m pip install guzzle_sphinx_theme

script:
  - cd docs
  - make html
  - cd _build/html
  - touch .nojekyll
  - touch CNAME
  - echo "docs.amsimp.com" > CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./docs/_build/html
  on:
    branch: master

after_success:
  - cd ..
  - cd ..
  - cd ..
  - coverage run tests.py
  - codecov
  