git:
  depth: false

script:
  - pip install sphinx
  - pip install guzzle_sphinx_theme

deploy:
  edge:
    branch: v1.8.47
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: public
    repo: amsimp/amsimp
    target-branch: master
    verbose: true
    on:
      branch: master