language: generic
os: osx

git:
  depth: false

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda init
  - source ~/miniconda/etc/profile.d/conda.sh
  - conda env create -f environment.yml && conda activate amsimp
  - pip install sphinx
  - pip install autoapi
  - pip install guzzle_sphinx_theme
  - pip install sphinxcontrib-bibtex
  - python setup.py install
  - cd docs
  - make clean && make html
  - cd _build/html
  - touch .nojekyll
  - touch CNAME
  - echo "https://docs.amsimp.com" > CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./docs/_build/html
  on:
    branch: dev