trigger:
- master

pool:
  vmImage: 'macOS-10.15'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.8'
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH
- bash: sudo chown -R $USER $CONDA
  displayName: Take ownership of conda installation
- job: build_environment
    displayName: Build Environment
    dependsOn: pre_build_setup
    steps:
      - script: conda env create -f environment.yml
        displayName: Create Anaconda environment
      - script: conda env list
        displayName:  environment installation verification
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            eval "$(conda shell.bash hook)"
            conda activate build_env
        displayName: Active
- bash: |
    python setup.py install
  displayName: Install Anaconda packages
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import amsimp

      state = amsimp.Dynamics(ai=False, forecast_length=6)

      state.simulate()

      state.exit()
