name: amsimp
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - python=3.7
  - pip
  - astropy
  - matplotlib
  - numpy
  - cartopy
  - pandas
  - scikit-learn
  - iris
  - progress
  - pip:
    - tensorflow==2.2.0 
