package:
  name: amsimp
  version: "1.0.0"

source:
  git_url: https://github.com/amsimp/amsimp.git

channels:
  - conda-forge
  - defaults

requirements:
  dependices:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - tqdm
    - pip:
      - tensorflow
  host:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - tqdm
    - pip:
      - tensorflow
  build:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - tqdm
  run:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - tqdm

test:
  imports:
    - amsimp

outputs:
  - name: amsimp-models
    files:
      - amsimp/rnn/models

about:
  home: https://amsimp.com
  license: GPL-3.0
  summary: Numerical Weather Prediction using Machine Learning
  description: AMSIMP is an open-source solution that leverages machine learning to improve numerical weather prediction.
  dev_url: https://github.com/amsimp/amsimp
  doc_url: https://docs.amsimp.com
  doc_source_url: https://github.com/amsimp/amsimp/tree/dev/docs
