package:
  name: amsimp
  version: "1.0.0"

source:
  git_url: https://github.com/amsimp/amsimp.git

channels:
  - conda-forge
  - defaults

requirements:
  dependices:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - pip:
      - tensorflow
  host:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - pip:
      - tensorflow
  build:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - pip:
      - tensorflow
  run:
    - cython
    - python=3.7
    - pip
    - astropy
    - matplotlib
    - numpy
    - cartopy
    - pandas
    - scikit-learn
    - iris
    - progress
    - pip:
      - tensorflow

test:
  imports:
    - amsimp

about:
  home: https://amsimp.com
  license: GPL-3.0
  summary: AMSIMP is an easy-to-use atmospheric dynamical core package in Python.
  description: An open-source, hydrostatic, atmospheric dynamical core using recurrent neural networks, written in the programming language of Cython. The aim of the software is to be a plugin that can be easily incorporated into weather and climate research projects.
  dev_url: https://github.com/amsimp/amsimp
  doc_url: https://docs.amsimp.com
  doc_source_url: https://github.com/amsimp/amsimp/tree/dev/docs
