package:
  name: amsimp
  version: "0.6.1"

source:
  git_url: https://github.com/amsimp/amsimp.git

channels:
  - conda-forge
  - defaults

requirements:
  build:
    - python
    - numpy
  host:
    - python
    - numpy
  dependices:
    - python
    - astropy
    - numpy
    - iris
    - tqdm
    - pip
    - pip:
      - tensorflow
  run:
    - python
    - astropy
    - numpy
    - iris
    - tqdm
    - pip

about:
  home: https://amsimp.com
  license: GPL-3.0
  summary: Numerical Weather Prediction using Machine Learning
  description: AMSIMP is an open-source solution that leverages machine learning to improve numerical weather prediction.
  dev_url: https://github.com/amsimp/amsimp
  doc_url: https://docs.amsimp.com
  doc_source_url: https://github.com/amsimp/amsimp/tree/dev/docspackage
  name: AMSIMP
  version: "0.6.1"
