name: Upload to Anaconda Cloud

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1  
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        elif [ "$RUNNER_OS" == "macOS" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        export PATH="$HOME/miniconda/bin:$PATH"
        which python
        conda init
    - name: Build Package
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init
        source ~/miniconda/etc/profile.d/conda.sh
        sudo conda env create -f environment.yml
        conda activate amsimp
        conda-build .
    - name: Upload to Anaconda Upload
      uses: fdiblen/anaconda-action@0.1.7
      with:
        envFileName: 'environment.yml'
        publish: 'true'
        publishChannel: 'AMSIMP'
        anacondaToken: $ANACONDA_PASSWORD
