name: Build AMSIMP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        export PATH="$HOME/miniconda/bin:$PATH"
        which python
        conda init
    - name: Test AMSIMP compilation and installation
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init
        source ~/miniconda/etc/profile.d/conda.sh
        sudo conda env create -f environment.yml
        sudo conda activate amsimp
        pip install tensorflow
        python setup.py install --user
        python test.py
