name: Upload and publish package to PyPI

on:
  push:
    tags:
       - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        export PATH="$HOME/miniconda/bin:$PATH"
        which python
        conda init
    - name: Test AMSIMP compilation and installation
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        source ~/miniconda/etc/profile.d/conda.sh
        source ~/.bashrc
        conda env create -f environment.yml
        conda activate amsimp
        python setup.py sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
