name: Upload to PyPi.

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        sudo apt install gcc
        export PATH="$HOME/miniconda/bin:$PATH"
        which python
        conda install numpy
        conda install pandas
        pip install setuptools
        conda install -c conda-forge cartopy
        conda install twine
    - name: Build PyPi Package.
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        which python
        python setup.py build_ext --inplace
        python setup.py sdist
